<a href="https://colab.research.google.com/github/Gliitchhh410/PyTorch_Fundmentals/blob/main/Pytorch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
rand_a = t.rand(3,4)
rand_b = t.rand(3,4)

print(rand_a)

print(rand_b)

print(rand_a == rand_b)

tensor([[0.8094, 0.7348, 0.9477, 0.2823],
        [0.3040, 0.1149, 0.3321, 0.6023],
        [0.2123, 0.7844, 0.4634, 0.3156]])
tensor([[0.8940, 0.7658, 0.3240, 0.0530],
        [0.7987, 0.5461, 0.9982, 0.0988],
        [0.9702, 0.6158, 0.8157, 0.2369]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
t.manual_seed(42)
rand_a = t.rand(3,4)
t.manual_seed(42)
rand_b = t.rand(3,4)

print(rand_a)

print(rand_b)

print(rand_a == rand_b)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Exercises and Extra Curriculum

In [ ]:
import torch as t

tensor_a = t.rand(7,7)
tensor_a

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
t.manual_seed(0)

tensor_a = t.rand(7,7)
print(tensor_a)


t.manual_seed(0)
tensor_b = t.rand(1,7)
print(tensor_b)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


In [ ]:
t.matmul(tensor_a, tensor_b.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
t.manual_seed(1234)



device = 'cuda' if t.cuda.is_available() else 'cpu'
print(f"Device: {device}")


tensor_c = t.rand(2,3).to(device)


tensor_d = t.rand(2,3).to(device)
tensor_c, tensor_d

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
out_tensor = t.matmul(tensor_c, tensor_d.T)
out_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [ ]:
print(t.min(out_tensor))
print(t.max(out_tensor))
print(t.argmin(out_tensor))
print(t.argmax(out_tensor))

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')
tensor(0, device='cuda:0')
tensor(3, device='cuda:0')


In [ ]:
t.manual_seed(7)


tensor_a = t.rand(1,1,1,10)
tensor_a, tensor_a.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
tensor_a = t.squeeze(tensor_a)
tensor_a, tensor_a.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))